spring:
  application:
    name: gateway
server:
  port: 8080
  use-forward-headers: true
zuul:
  routes:
    person-service:
      path: /person/**
eureka:
  client:
    serviceUrl:
      defaulZone: http://localhost:8761/eureka
